version: "3"
services:
  minio:
    image: quay.io/minio/minio
    command:
      - server
      - /data
      - --console-address
      - ":9001"
  ufys:
    build: ufys
    environment:
      MINIO_SECURE: ""
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ufys
      MINIO_ENDPOINT: minio:9000
  ew:
    build: .
    environment:
      BASE_HOSTS: localhost,ew.tunnel.771.blue
      UFYS_URL: http://ufys
    ports:
      - "5001:80"
